version: '3.8'

services:
  frontend:
    image: 'avito-frontend-dev'
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./client/src:/app/src
  api:
    image: ipotemkin/skyavito_api:v1.7
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server/data:/code/data # to get to the database
      - ./server/data/ad_images:/code/ad_images # to get to ads images
      - ./server/data/avatar_images:/code/avatar_images # to get to avatar images
    environment:
      - AC_TOKEN_EXP_TIME_MIN=5 # access token lifetime in minutes
      - R_TOKEN_EXP_TIME_MIN=1440 # =24 hours # refresh token lifetime in minutes
    ports:
      - '127.0.0.1:8090:80'
    depends_on:
      migrations:
        condition: service_completed_successfully
    restart: always

    command: uvicorn --host 0.0.0.0 --port 80 app:app # --workers 4

  migrations:
    image: ipotemkin/skyavito_api:v1.7
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server/data:/code/data # to get to the database
      - ./server/data/ad_images:/code/ad_images # to get to ads images
      - ./server/data/avatar_images:/code/avatar_images # to get to avatar images
    command: >
      sh -c "alembic upgrade head"
